import '../models/menu_item.dart';

final List<MenuItem> pizzas = [
  MenuItem(
    name: 'Margherita',
    category: 'Pizza',
    description: 'Classic cheesy delight with a tangy tomato base.',
    price: 180,
    imagePath: 'assets/pizzas/pizza_1.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Farmhouse',
    category: 'Pizza',
    description: 'Loaded with fresh veggies for a wholesome bite.',
    price: 210,
    imagePath: 'assets/pizzas/pizza_2.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Peppy Paneer',
    category: 'Pizza',
    description: 'Zesty paneer chunks with a spicy veggie twist.',
    price: 240,
    imagePath: 'assets/pizzas/pizza_3.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Veggie Paradise',
    category: 'Pizza',
    description: 'A veggie lover’s dream on a cheesy base.',
    price: 270,
    imagePath: 'assets/pizzas/pizza_4.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Deluxe Veggie',
    category: 'Pizza',
    description: 'Rich, hearty, and brimming with flavors.',
    price: 300,
    imagePath: 'assets/pizzas/pizza_5.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Mexican Green Wave',
    category: 'Pizza',
    description: 'Spicy Mexican flavors with crunchy veggies.',
    price: 330,
    imagePath: 'assets/pizzas/pizza_6.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Cheese n Corn',
    category: 'Pizza',
    description: 'Sweet corn meets gooey cheese perfection.',
    price: 180,
    imagePath: 'assets/pizzas/pizza_7.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Fresh Veggie',
    category: 'Pizza',
    description: 'Crisp veggies on a bed of cheesy goodness.',
    price: 210,
    imagePath: 'assets/pizzas/pizza_8.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Paneer Makhani',
    category: 'Pizza',
    description: 'Creamy makhani sauce topped with soft paneer.',
    price: 240,
    imagePath: 'assets/pizzas/pizza_9.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Double Cheese Margherita',
    category: 'Pizza',
    description: 'Twice the cheese, twice the happiness.',
    price: 270,
    imagePath: 'assets/pizzas/pizza_10.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Veg Extravaganza',
    category: 'Pizza',
    description: 'Overflowing with veggies and cheese overload.',
    price: 300,
    imagePath: 'assets/pizzas/pizza_11.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Indi Tandoori Paneer',
    category: 'Pizza',
    description: 'Smoky tandoori paneer with Indian spices.',
    price: 330,
    imagePath: 'assets/pizzas/pizza_12.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Spicy Triple Tango',
    category: 'Pizza',
    description: 'Three layers of fiery, tangy, cheesy fun.',
    price: 180,
    imagePath: 'assets/pizzas/pizza_13.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Tandoori Veggie',
    category: 'Pizza',
    description: 'Char-grilled veggies with smoky flavors.',
    price: 210,
    imagePath: 'assets/pizzas/pizza_14.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Achari Do Pyaza',
    category: 'Pizza',
    description: 'Tangy achari punch with double onions.',
    price: 240,
    imagePath: 'assets/pizzas/pizza_15.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Veg Loaded',
    category: 'Pizza',
    description: 'Packed with colorful veggies in every bite.',
    price: 270,
    imagePath: 'assets/pizzas/pizza_16.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Creamy Tomato Delight',
    category: 'Pizza',
    description: 'Smooth tomato sauce with a creamy finish.',
    price: 300,
    imagePath: 'assets/pizzas/pizza_17.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Paneer Special',
    category: 'Pizza',
    description: 'Generous paneer cubes with cheesy topping.',
    price: 330,
    imagePath: 'assets/pizzas/pizza_18.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Corn & Cheese Burst',
    category: 'Pizza',
    description: 'Cheese bursting with sweet corn bites.',
    price: 180,
    imagePath: 'assets/pizzas/pizza_19.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
  MenuItem(
    name: 'Mozzarella Cheese Pizza',
    category: 'Pizza',
    description: 'Melty mozzarella magic on every slice.',
    price: 210,
    imagePath: 'assets/pizzas/pizza_20.png',
    allowedCustomizations: ['Extra Cheese','Onion','Tomato','Paneer','Mushroom','Corn','Olives','Jalapeños','Capsicum'],
  ),
];

final List<MenuItem> garlics = [
  MenuItem(
    name: 'Classic Garlic Breadsticks',
    category: 'Garlic',
    description: 'Buttery garlic sticks — crisp outside, soft inside.',
    price: 120,
    imagePath: 'assets/garlic/garlic_1.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Cheese Garlic Bread',
    category: 'Garlic',
    description: 'Golden garlic bread lavishly topped with gooey cheese.',
    price: 135,
    imagePath: 'assets/garlic/garlic_2.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Stuffed Garlic Bread',
    category: 'Garlic',
    description: 'Loaded with melty cheese inside — bite-sized bliss.',
    price: 150,
    imagePath: 'assets/garlic/garlic_3.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Jalapeño Garlic Bread',
    category: 'Garlic',
    description: 'Garlic bread with a spicy jalapeño kick — zesty & bold.',
    price: 165,
    imagePath: 'assets/garlic/garlic_4.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Cheese Burst Garlic Bread',
    category: 'Garlic',
    description: 'Exploding with molten cheese and garlicky goodness.',
    price: 120,
    imagePath: 'assets/garlic/garlic_5.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Onion & Cheese Garlic Bread',
    category: 'Garlic',
    description: 'Caramelized onion and melted cheese on a garlic base.',
    price: 135,
    imagePath: 'assets/garlic/garlic_6.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Paneer Stuffed Garlic Bread',
    category: 'Garlic',
    description: 'Soft paneer-stuffed bites with rich garlic butter.',
    price: 150,
    imagePath: 'assets/garlic/garlic_7.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Corn & Cheese Garlic Bread',
    category: 'Garlic',
    description: 'Sweet corn and molten cheese on a garlicky toast.',
    price: 165,
    imagePath: 'assets/garlic/garlic_8.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Herb & Cheese Garlic Bread',
    category: 'Garlic',
    description: 'Fragrant herbs and gooey cheese — herbaceous treat.',
    price: 120,
    imagePath: 'assets/garlic/garlic_9.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
  MenuItem(
    name: 'Cheesy Jalapeño Dip Bread',
    category: 'Garlic',
    description: 'Cheesy bread served with a spicy jalapeño dip.',
    price: 135,
    imagePath: 'assets/garlic/garlic_10.png',
    allowedCustomizations: ['Extra Cheese'],
  ),
];

final List<MenuItem> bevs = [
  MenuItem(
    name: 'Coca-Cola',
    category: 'Beverage',
    description: 'Classic fizzy cola, perfectly chilled.',
    price: 40,
    imagePath: 'assets/beverages/bev_1.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Pepsi',
    category: 'Beverage',
    description: 'Bold cola fizz to lift your spirits.',
    price: 50,
    imagePath: 'assets/beverages/bev_2.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Sprite',
    category: 'Beverage',
    description: 'Crisp lemon-lime fizz — ultra refreshing.',
    price: 60,
    imagePath: 'assets/beverages/bev_3.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Fanta',
    category: 'Beverage',
    description: 'Fruity orange fizz that zings with every sip.',
    price: 70,
    imagePath: 'assets/beverages/bev_4.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Thums Up',
    category: 'Beverage',
    description: 'Strong cola with a bold, fizzy kick.',
    price: 80,
    imagePath: 'assets/beverages/bev_5.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Mountain Dew',
    category: 'Beverage',
    description: 'Citrusy energy fizz — tangy and vibrant.',
    price: 40,
    imagePath: 'assets/beverages/bev_6.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Maaza',
    category: 'Beverage',
    description: 'Sweet mango sip bursting with summer vibes.',
    price: 50,
    imagePath: 'assets/beverages/bev_7.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: '7Up',
    category: 'Beverage',
    description: 'Light lemon-lime sparkle — super refreshing.',
    price: 60,
    imagePath: 'assets/beverages/bev_8.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Limca',
    category: 'Beverage',
    description: 'Tangy lime soda with a cool, zesty kick.',
    price: 70,
    imagePath: 'assets/beverages/bev_9.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Diet Coke',
    category: 'Beverage',
    description: 'Zero-sugar cola, all the taste, less guilt.',
    price: 80,
    imagePath: 'assets/beverages/bev_10.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Red Bull',
    category: 'Beverage',
    description: 'Energy boost in a can to power your day.',
    price: 40,
    imagePath: 'assets/beverages/bev_11.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Tropicana Orange Juice',
    category: 'Beverage',
    description: 'Fresh orange juice — bright and naturally sweet.',
    price: 50,
    imagePath: 'assets/beverages/bev_12.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Tropicana Apple Juice',
    category: 'Beverage',
    description: 'Crisp apple juice with a clean, sweet finish.',
    price: 60,
    imagePath: 'assets/beverages/bev_13.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'B Natural Mixed Fruit Juice',
    category: 'Beverage',
    description: 'A medley of fruits for a fruity, refreshing sip.',
    price: 70,
    imagePath: 'assets/beverages/bev_14.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Paper Boat Aam Panna',
    category: 'Beverage',
    description: 'Tangy aam panna — the perfect summer cooler.',
    price: 80,
    imagePath: 'assets/beverages/bev_15.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Paper Boat Jaljeera',
    category: 'Beverage',
    description: 'Spiced jaljeera with tangy minty notes.',
    price: 40,
    imagePath: 'assets/beverages/bev_16.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Bisleri Water 500ml',
    category: 'Beverage',
    description: 'Pure, refreshing bottled water.',
    price: 50,
    imagePath: 'assets/beverages/bev_17.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Bisleri Water 1L',
    category: 'Beverage',
    description: 'Hydration in a handy 1L bottle.',
    price: 60,
    imagePath: 'assets/beverages/bev_18.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Appy Fizz',
    category: 'Beverage',
    description: 'Sparkling apple drink with a fizzy twist.',
    price: 70,
    imagePath: 'assets/beverages/bev_19.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
  MenuItem(
    name: 'Ginger Ale',
    category: 'Beverage',
    description: 'Ginger-flavored fizz with a gentle spicy bite.',
    price: 80,
    imagePath: 'assets/beverages/bev_20.png',
    allowedCustomizations: ['Normal', 'Cold', 'Very Cold'],
  ),
];
